spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 4MB # This allows us to upload 2 requests simultaneously
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://192.168.1.6/backend
    username: mysql
    password: Welcome1
#    url: jdbc:postgresql://localhost:5432/backend
#    username: postgres
#    password: syspass
#    url: jdbc:mysql://localhost/backend
#    username: mysql
#    password: syspass

logging:
  level:
    org.springframework: INFO


management:
  endpoints:
    enabled-by-default: true
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true
  health:
    key:
      enabled: [
          "db"]

info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"