spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 4MB # This allows us to upload 2 requests simultaneously
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    url: jdbc:mysql://localhost/backend
#    username: mysql
#    password: syspass
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass

